version: "3.9"
services:
  mykinolist-api:
    build: ./
    command: make
    environment:
      DB_PASSWORD: qwerty
      JWT_ACCESS_SECRET_KEY: SomeAccessTokenSecretKey
      JWT_REFRESH_SECRET_KEY: SomeRefreshTokenSecretKey
      KINOPOISK_API_KEY: # your secret kinopoisk api key
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_started
  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/database
    command:
      [ "-path", "/database", "-database",  "postgres://kirrryu:qwerty@postgres:5432/mykinolist?sslmode=disable", "up" ]
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_DB: "mykinolist"
      POSTGRES_USER: "kirrryu"
      POSTGRES_PASSWORD: "qwerty"
    volumes:
      - ./.database/postgres/data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U kirrryu -d mykinolist'"]
      interval: 10s
      timeout: 3s
      retries: 3